bases:
  - ./bases/environments.yaml
  - ./bases/infrastructure.yaml

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  # Postgres
  - name: postgres
    namespace: postgres
    chart: bitnami/postgresql
    inherit:
      - template: infrastructure
    # values:
    #   - ./values/common/postgres.yaml.gotmpl
