commonLabels:
  tenant: {{ .Values.tenant }}
  application: true

templates:
  application:
    name: application-{{ .Values.tenant }}-{{`{{ .Release.Labels.application }}`}}
    chart: ../charts/application
    namespace: application-{{ .Values.tenant }}
    missingFileHandler: Warn
    valuesTemplate:
      - ../values/app-common/values.yaml
      - ../values/{{`{{ .Release.Labels.application }}`}}/values.yaml
      - ../values/{{`{{ .Release.Labels.application }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
      - ../values/{{`{{ .Release.Labels.application }}`}}/secrets.yaml
      - ../values/{{`{{ .Release.Labels.application }}`}}/{{`{{ .Environment.Name }}`}}-secrets.yaml
