# bases:
#   - helmfiles/bases/environments.yaml

environments:
  default:
    values:
      - values/default.yaml
  test:
    values:
      - values/test.yaml
  production:
    values:
      - values/production.yaml

helmfiles:
  - path: ./helmfiles/*.yaml
    values:
      - tenant: {{ requiredEnv "ES_TENANT" }}
